#!/bin/sh

# Script para abrir arquivos no editor de texto usando o dmenu
exec > /dev/null 2>&1

[ -d "$1" ] && cd "$1"

selection=$( ls -ap1 --group-directories-first | dmenu -i -l 15 )

while [ -d "$selection" ]
do
	cd "$selection"
	selection=$( ls -ap1 --group-directories-first | dmenu -i -l 15 )
done

[ -e "$selection" ] && echo "$selection" | while read file
do
	st -e nvim "$file" &
done

exit 0
