#!/bin/sh
exec > /dev/null 2>&1

dirs="Biblioteca/Fichamentos/ R/  .config/nvim/  .config/zsh/"
find $(echo $dirs) -print | dmenu -i -l 20 -fn 16 | \
while read opt
do
	$TERMINAL -e $EDITOR "$opt" &
done
