#!/bin/sh
#
# Descrição: Gera lista de palavras que pode ser usada como entrada para funções
#            de auto-completar (como em editores de texto)
#------------------------------------------------------------------------------

word_list() {
	sed 's/[[:punct:][:digit:]]//g' $1 |\
	sed 's/\s/\n/g'
}
	
usage() {
	echo "Uso: $(basename  $0) [-f file1 file2 ...] [-d dir1 dir2 ...] [-o output file]\n
	-h, --help\n
	-f, --files        lista de arquivos de entrada\n
	-d, --directories  lista de diretórios de entrada\n
	-o, --output       saída padrão para o arquivo $PWD/word-list.txt"
}
		
input=''                # lista de arquivos gerada a partir das opções -f e -d
temp=$(mktemp)          # arquivo temporário
output="word-list.txt"  # destino padrão de saída

# loop para preencher a variável $input com o texto dos arquivos
while [ $# -gt 0 ]; do
	case "$1" in
	-h|--help)
		usage
		exit 0
		;;
	-o|--output)
		output="$2"
		shift 2
		;;
	-d|--dirs)
		shift
		read -p "sufixo/padrão de busca (e.g. '.sh', '[padrão]', ''): " sufix
		while [ -d "$1" ]; do
			input="${input}$(find "$1" -type f -iname "*$sufix" -print)\n"
			shift
		done
		;;
	-f|--files)
		shift
		while [ -f $1 ]; do
			input="${input}$1\n"
			shift
		done
		;;
	*)
		echo "Argumentos incorretos.\n$(usage)."
		exit 1
		;;
	esac
done

echo "$input" | while read i; do
	word_list "$i" >> $temp
done
sort -u $temp >> "$output"

exit 0
